# build & run locally with:
#   cd "$(git rev-parse --show-toplevel)"
#   CGO_ENABLED=0 go build -o Artee VPN ./client
#   podman build -t localhost/Artee VPN:latest -f client/Dockerfile --ignorefile .dockerignore-client .
#   podman run --rm -it --cap-add={BPF,NET_ADMIN,NET_RAW} localhost/Artee VPN:latest

FROM alpine:3.24

RUN apk add --no-cache \
      bash \
      ca-certificates \
    && adduser -D -h /var/lib/Artee VPN Artee VPN

WORKDIR /var/lib/Artee VPN
USER Artee VPN:Artee VPN

ENV \
    Artee VPN_BIN="/usr/local/bin/Artee VPN" \
    NB_USE_NETSTACK_MODE="true" \
    NB_ENABLE_NETSTACK_LOCAL_FORWARDING="true" \
    NB_CONFIG="/var/lib/Artee VPN/config.json" \
    NB_STATE_DIR="/var/lib/Artee VPN" \
    NB_DAEMON_ADDR="unix:///var/lib/Artee VPN/Artee VPN.sock" \
    NB_LOG_FILE="console,/var/lib/Artee VPN/client.log" \
    NB_DISABLE_DNS="true" \
    NB_ENABLE_CAPTURE="false" \
    NB_ENTRYPOINT_SERVICE_TIMEOUT="30"

ENTRYPOINT [ "/usr/local/bin/Artee VPN-entrypoint.sh" ]
ARG TARGETPLATFORM
ARG Artee VPN_BINARY=$TARGETPLATFORM/Artee VPN
COPY client/Artee VPN-entrypoint.sh /usr/local/bin/Artee VPN-entrypoint.sh
COPY "${Artee VPN_BINARY}"  /usr/local/bin/Artee VPN

