<?php
/**
 * ROOFIQ — Reports List
 * PHP 7.0.1 Compatible
 */
require_once dirname(__DIR__) . '/src/config.php';
require_once dirname(__DIR__) . '/src/db.php';
require_once dirname(__DIR__) . '/src/functions.php';
session_start_safe();
require_login();

$reports = db_fetch_all(
    "SELECT r.*, p.address, p.formatted_address, u.full_name as generated_by_name
     FROM reports r
     LEFT JOIN properties p ON p.id=r.property_id
     LEFT JOIN users u ON u.id=r.generated_by
     ORDER BY r.generated_at DESC"
);

// Also show all analyses as potential reports
$analyses = db_fetch_all(
    "SELECT ra.*, p.address, p.formatted_address, u.full_name as analyzed_by_name
     FROM roof_analysis ra
     LEFT JOIN properties p ON p.id=ra.property_id
     LEFT JOIN users u ON u.id=ra.analyzed_by
     WHERE ra.status='Complete'
     ORDER BY ra.created_at DESC LIMIT 100"
);

include_page_header('Reports');
page_content_header('Report History', array('Reports' => ''));
?>

<!-- Analyses available for PDF -->
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-satellite-dish mr-2" style="color:#00e676;"></i>Completed Analyses — Generate PDF
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
    </div>
  </div>
  <div class="card-body p-0">
    <div class="table-responsive">
    <table class="table table-sm mb-0">
      <thead>
        <tr><th>Address</th><th>Roof Area</th><th>Condition</th><th>Analyzed By</th><th>Date</th><th>Actions</th></tr>
      </thead>
      <tbody>
        <?php if (empty($analyses)): ?>
          <tr><td colspan="6" class="text-center text-muted py-4">
            No completed analyses yet. <a href="analysis.php">Analyze a property</a>.
          </td></tr>
        <?php else: foreach ($analyses as $ra): ?>
          <tr>
            <td>
              <a href="analysis.php?property_id=<?php echo e($ra['property_id']); ?>" style="color:#00d4ff;font-size:0.88rem;">
                <?php echo e(substr($ra['formatted_address'] ? $ra['formatted_address'] : $ra['address'], 0, 50)); ?>
              </a>
            </td>
            <td><?php echo $ra['roof_area_sqft'] ? number_format($ra['roof_area_sqft']) . ' sf' : '—'; ?></td>
            <td>
              <?php if ($ra['condition_score']): ?>
                <span style="color:<?php echo $ra['condition_score'] >= 75 ? '#00e676' : ($ra['condition_score'] >= 60 ? '#ffd600' : '#ff6b35'); ?>">
                  <?php echo $ra['condition_score']; ?>/100
                </span>
                <span class="text-muted" style="font-size:0.78rem;"><?php echo e($ra['condition_label']); ?></span>
              <?php else: ?>—<?php endif; ?>
            </td>
            <td style="font-size:0.78rem;color:#94a3b8;"><?php echo e($ra['analyzed_by_name'] ? $ra['analyzed_by_name'] : '—'); ?></td>
            <td style="font-size:0.78rem;color:#94a3b8;"><?php echo fmt_date($ra['created_at']); ?></td>
            <td>
              <div style="display:flex;gap:6px;align-items:center;">
              <a href="report/generate.php?property_id=<?php echo e($ra['property_id']); ?>&analysis_id=<?php echo e($ra['id']); ?>"
                 target="_blank" class="btn btn-sm btn-roofiq-danger">
                <i class="fas fa-file-pdf mr-1"></i>PDF
              </a>
              <a href="analysis.php?property_id=<?php echo e($ra['property_id']); ?>"
                 class="btn btn-sm btn-outline-info">View</a>
              </div>
            </td>
          </tr>
        <?php endforeach; endif; ?>
      </tbody>
    </table>
    </div><!-- /table-responsive -->
  </div>
</div>

<!-- Report History -->
<?php if (!empty($reports)): ?>
<div class="card">
  <div class="card-header"><i class="fas fa-history mr-2" style="color:#94a3b8;"></i>Report Download History</div>
  <div class="card-body p-0">
    <table class="table table-sm mb-0">
      <thead>
        <tr><th>Address</th><th>Report Type</th><th>Generated By</th><th>Date</th></tr>
      </thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
          <tr>
            <td style="font-size:0.85rem;color:#e2e8f0;"><?php echo e(substr($r['formatted_address'] ? $r['formatted_address'] : $r['address'], 0, 60)); ?></td>
            <td><span class="badge badge-secondary"><?php echo e($r['report_type']); ?></span></td>
            <td style="font-size:0.78rem;color:#94a3b8;"><?php echo e($r['generated_by_name'] ? $r['generated_by_name'] : '—'); ?></td>
            <td style="font-size:0.78rem;color:#94a3b8;"><?php echo fmt_date($r['generated_at']); ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
<?php endif; ?>

<?php
page_content_footer();
include_page_footer();
?>
